.github/PULL_REQUEST_TEMPLATE.md

INTERNAL:CAP-18 - Create PR Template

---

.github/PULL_REQUEST_TEMPLATE.md

**JIRA Ticket:** [CAP-18](https://mfslcapstone.atlassian.net/browse/CAP-18)
**Summary:**
**Screenshots/Examples:**
**Dependencies:**
---
[CAP-18]: https://mfslcapstone.atlassian.net/browse/CAP-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INTERNAL:CAP-18 - Update PR Template

---

README.Md

**JIRA Ticket:** NA
**Summary:**
**Screenshots/Examples:**
**Dependencies:**
---

INTERNAL: UPDATE README.MD INSTRUCTIONS

---

pom.xml
src/test/java/capstone/mfslbackend/service/PlayerServiceTest.java
src/test/java/capstone/mfslbackend/service/TeamServiceTest.java

**JIRA Ticket:** 
- [CAP-23](https://mfslcapstone.atlassian.net/browse/CAP-23)
**Summary:**
@abhijeetpraveen If we have well written tickets, we shouldn't need this since we point to the ticket at the top of the PR, so the reviewer can go there for a description of the work
Unit tests were written using JUnit4, but the Spring configuration forces us to use JUnit5 to run tests, so we have to switch all the existing tests to JUnit5
**Screenshots/Examples:**
No siree, I forgot to do this for my branch and commit lol
Deleted a dependency to JUnit4, now for the tests, the only dependency is:
```
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-test</artifactId>
<scope>test</scope>
</dependency>
```
---
[CAP-23]: …

FIX:CAP-23 Fix Unit Tests

---

.github/PULL_REQUEST_TEMPLATE.md

**JIRA Ticket:** [CAP-26](https://mfslcapstone.atlassian.net/browse/CAP-26)
**Summary:**
**Screenshots/Examples:**
---
[CAP-26]: https://mfslcapstone.atlassian.net/browse/CAP-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INTERNAL: CAP-26 - Remove summary section from PR template

---

src/main/java/capstone/mfslbackend/controller/StatsController.java
src/main/java/capstone/mfslbackend/model/Game.java
src/main/java/capstone/mfslbackend/model/Player.java
src/main/java/capstone/mfslbackend/model/PlayerGameStats.java
src/main/java/capstone/mfslbackend/repository/PlayerGameStatsRepository.java
src/main/java/capstone/mfslbackend/response/container/StatsContainer.java
src/main/java/capstone/mfslbackend/response/dto/PlayerStatsResponse.java
src/main/java/capstone/mfslbackend/response/dto/PlayersStatsResponse.java
src/main/java/capstone/mfslbackend/response/dto/TeamResponse.java
src/main/java/capstone/mfslbackend/response/dto/TeamsResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/CardResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/DribbleResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/DuelResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/FoulResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/GoalResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/PassResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/PenaltyResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/ShotResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/StatisticResponse.java
src/main/java/capstone/mfslbackend/response/dto/stats/TackleResponse.java
src/main/java/capstone/mfslbackend/service/PlayerGameStatsService.java
src/main/java/capstone/mfslbackend/service/PlayerService.java
src/test/java/capstone/mfslbackend/service/PlayerGameStatsServiceTest.java
src/test/java/capstone/mfslbackend/service/PlayerServiceTest.java

CAP-20 create stats

---

src/main/java/capstone/mfslbackend/controller/TransactionController.java
src/main/java/capstone/mfslbackend/model/Transaction.java
src/main/java/capstone/mfslbackend/repository/TransactionRepository.java
src/main/java/capstone/mfslbackend/service/TransactionService.java
src/test/java/capstone/mfslbackend/service/TransactionServiceTest.java

**JIRA Ticket:** [CAP-35](https://mfslcapstone.atlassian.net/browse/CAP-35)
---
[CAP-35]: https://mfslcapstone.atlassian.net/browse/CAP-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-35 Create Transactions Class

---

src/main/java/capstone/mfslbackend/controller/FantasyLeagueController.java
src/main/java/capstone/mfslbackend/model/FantasyLeague.java
src/main/java/capstone/mfslbackend/model/Game.java
src/main/java/capstone/mfslbackend/repository/FantasyLeagueRepository.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java
src/test/java/capstone/mfslbackend/service/FantasyLeagueServiceTest.java

**JIRA Ticket:** [CAP-33](https://mfslcapstone.atlassian.net/browse/CAP-33)
---
[CAP-33]: https://mfslcapstone.atlassian.net/browse/CAP-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-33 Create Fantasy League

---

src/main/java/capstone/mfslbackend/controller/FantasyTeamController.java
src/main/java/capstone/mfslbackend/controller/FantasyWeekController.java
src/main/java/capstone/mfslbackend/model/FantasyTeam.java
src/main/java/capstone/mfslbackend/model/FantasyWeek.java
src/main/java/capstone/mfslbackend/repository/FantasyTeamRepository.java
src/main/java/capstone/mfslbackend/repository/FantasyWeekRepository.java
src/main/java/capstone/mfslbackend/service/FantasyTeamService.java
src/main/java/capstone/mfslbackend/service/FantasyWeekService.java

**JIRA Ticket:** [CAP-32](https://mfslcapstone.atlassian.net/browse/CAP-32)
**JIRA Ticket:** [CAP-34](https://mfslcapstone.atlassian.net/browse/CAP-34)
---
[CAP-32]: https://mfslcapstone.atlassian.net/browse/CAP-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CAP-34]: https://mfslcapstone.atlassian.net/browse/CAP-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FEAT: CAP-32/CAP-34 - Create FantasyTeam/FantasyWeek Classes

---

src/main/java/capstone/mfslbackend/configuration/SecurityConfiguration.java
src/main/java/capstone/mfslbackend/controller/FantasyLeagueController.java
src/main/java/capstone/mfslbackend/model/FantasyLeague.java
src/main/java/capstone/mfslbackend/model/User.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java
src/test/java/capstone/mfslbackend/service/FantasyLeagueServiceTest.java

**JIRA Ticket:** [CAP-47](https://mfslcapstone.atlassian.net/browse/CAP-47)
---
[CAP-47]: https://mfslcapstone.atlassian.net/browse/CAP-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FEAT:CAP-47 - Add User to FantasyLeague Functionality

---

src/main/java/capstone/mfslbackend/controller/FantasyWeekController.java
src/main/java/capstone/mfslbackend/model/FantasyTeam.java
src/main/java/capstone/mfslbackend/model/FantasyWeek.java
src/main/java/capstone/mfslbackend/service/FantasyWeekService.java

**JIRA Ticket:** [CAP-49](https://mfslcapstone.atlassian.net/browse/CAP-49)
---
[CAP-49]: https://mfslcapstone.atlassian.net/browse/CAP-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FEAT: CAP-49 - Create FantasyTeam to FantasyWeek Association

---

src/main/java/capstone/mfslbackend/controller/FantasyLeagueController.java
src/main/java/capstone/mfslbackend/model/FantasyLeague.java
src/main/java/capstone/mfslbackend/model/FantasyTeam.java
src/main/java/capstone/mfslbackend/model/User.java
src/main/java/capstone/mfslbackend/repository/UserRepository.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java
src/main/java/capstone/mfslbackend/service/LoginService.java
src/main/java/capstone/mfslbackend/service/UserService.java
src/test/java/capstone/mfslbackend/service/FantasyLeagueServiceTest.java

**JIRA Ticket:** [CAP-59](https://mfslcapstone.atlassian.net/browse/CAP-59)
---
[CAP-59]: https://mfslcapstone.atlassian.net/browse/CAP-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-59 Fix user to fantasy league assoc

---

src/main/java/capstone/mfslbackend/DTO/FantasyTeamLineup.java
src/main/java/capstone/mfslbackend/controller/FantasyTeamController.java
src/main/java/capstone/mfslbackend/model/FantasyTeam.java
src/main/java/capstone/mfslbackend/service/FantasyTeamService.java
src/main/java/capstone/mfslbackend/service/TransactionService.java

**JIRA Ticket:** [CAP-44](https://mfslcapstone.atlassian.net/browse/CAP-44)
---
[CAP-44]: https://mfslcapstone.atlassian.net/browse/CAP-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-44 Endpoints to get and set Fantasy Team Lineup

---

src/main/java/capstone/mfslbackend/DTO/FantasyLeaguePlayer.java
src/main/java/capstone/mfslbackend/MfslBackendApplication.java
src/main/java/capstone/mfslbackend/controller/FantasyLeagueController.java
src/main/java/capstone/mfslbackend/controller/FantasyTeamController.java
src/main/java/capstone/mfslbackend/controller/PlayerController.java
src/main/java/capstone/mfslbackend/controller/TeamController.java
src/main/java/capstone/mfslbackend/repository/PlayerRepository.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java
src/main/java/capstone/mfslbackend/service/PlayerService.java
src/main/resources/application.properties
src/test/java/capstone/mfslbackend/service/FantasyLeagueServiceTest.java

**JIRA Ticket:** [CAP-61](https://mfslcapstone.atlassian.net/browse/CAP-61)
---
[CAP-61]: https://mfslcapstone.atlassian.net/browse/CAP-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-61 get all players endpoint

---

src/main/java/capstone/mfslbackend/configuration/CustomExceptionHandler.java
src/main/java/capstone/mfslbackend/controller/FantasyLeagueController.java
src/main/java/capstone/mfslbackend/controller/FantasyTeamController.java
src/main/java/capstone/mfslbackend/controller/FantasyWeekController.java
src/main/java/capstone/mfslbackend/controller/GameController.java
src/main/java/capstone/mfslbackend/controller/PlayerController.java
src/main/java/capstone/mfslbackend/controller/StatsController.java
src/main/java/capstone/mfslbackend/controller/TeamController.java
src/main/java/capstone/mfslbackend/controller/TransactionController.java
src/main/java/capstone/mfslbackend/error/Error400.java
src/main/java/capstone/mfslbackend/error/Error404.java
src/main/java/capstone/mfslbackend/error/Error500.java
src/main/java/capstone/mfslbackend/model/Game.java
src/main/java/capstone/mfslbackend/model/Player.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java
src/main/java/capstone/mfslbackend/service/FantasyTeamService.java
src/main/java/capstone/mfslbackend/service/FantasyWeekService.java
src/main/java/capstone/mfslbackend/service/GameService.java
src/main/java/capstone/mfslbackend/service/LoginService.java
src/main/java/capstone/mfslbackend/service/PlayerGameStatsService.java
src/main/java/capstone/mfslbackend/service/PlayerService.java
src/main/java/capstone/mfslbackend/service/TeamService.java
src/main/java/capstone/mfslbackend/service/TransactionService.java
src/main/java/capstone/mfslbackend/service/UserService.java
src/test/java/capstone/mfslbackend/service/FantasyLeagueServiceTest.java
src/test/java/capstone/mfslbackend/service/PlayerGameStatsServiceTest.java

**JIRA Ticket:** [CAP-62](https://mfslcapstone.atlassian.net/browse/CAP-62)
---
[CAP-62]: https://mfslcapstone.atlassian.net/browse/CAP-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat/cap 62/controller advice

---

src/main/java/capstone/mfslbackend/configuration/WebConfig.java

**JIRA Ticket:** [CAP-66](https://mfslcapstone.atlassian.net/browse/CAP-66)
---
[CAP-66]: https://mfslcapstone.atlassian.net/browse/CAP-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add cors so frontend can communicate with backend

---

src/main/java/capstone/mfslbackend/configuration/WebConfig.java

**JIRA Ticket:** [XXX-###](https://mfslcapstone.atlassian.net/browse/XXX-###)
---

Feat/cap 66/configure cors

---

src/main/java/capstone/mfslbackend/controller/GameController.java
src/main/java/capstone/mfslbackend/model/Game.java
src/main/java/capstone/mfslbackend/model/Transaction.java
src/main/java/capstone/mfslbackend/repository/GameRepository.java
src/main/java/capstone/mfslbackend/response/dto/GamesResponse.java
src/main/java/capstone/mfslbackend/service/GameService.java
src/main/java/capstone/mfslbackend/service/TransactionService.java

**JIRA Ticket:** [CAP-60](https://mfslcapstone.atlassian.net/browse/CAP-60)
---
[CAP-60]: https://mfslcapstone.atlassian.net/browse/CAP-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-60 Get games by date

---

src/main/java/capstone/mfslbackend/model/PlayerGameStats.java
src/main/java/capstone/mfslbackend/service/PlayerGameStatsService.java

**JIRA Ticket:** [CAP-70](https://mfslcapstone.atlassian.net/browse/CAP-70)
---
[CAP-70]: https://mfslcapstone.atlassian.net/browse/CAP-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-70 association game stats to game

---

src/main/java/capstone/mfslbackend/controller/PlayerController.java
src/main/java/capstone/mfslbackend/service/PlayerService.java

**JIRA Ticket:** [CAP-73](https://mfslcapstone.atlassian.net/browse/CAP-73)
---
[CAP-73]: https://mfslcapstone.atlassian.net/browse/CAP-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Get player's game stats

---

src/main/java/capstone/mfslbackend/controller/PlayerController.java
src/main/java/capstone/mfslbackend/service/PlayerService.java
src/test/java/capstone/mfslbackend/service/PlayerServiceTest.java

**JIRA Ticket:** [CAP-74](https://mfslcapstone.atlassian.net/browse/CAP-74)
---
[CAP-74]: https://mfslcapstone.atlassian.net/browse/CAP-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Get player's future games

---

checkstyle.xml
src/main/java/capstone/mfslbackend/model/FantasyWeek.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java

**JIRA Ticket:** [CAP-68](https://mfslcapstone.atlassian.net/browse/CAP-68)
---
[CAP-68]: https://mfslcapstone.atlassian.net/browse/CAP-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP68 - Add Real Time Logic to Draft Order

---

src/main/java/capstone/mfslbackend/controller/GameController.java
src/main/java/capstone/mfslbackend/controller/StatsController.java
src/main/java/capstone/mfslbackend/model/Game.java
src/main/java/capstone/mfslbackend/service/GameService.java
src/main/java/capstone/mfslbackend/service/PlayerGameStatsService.java
src/main/java/capstone/mfslbackend/service/PlayerService.java
src/main/java/capstone/mfslbackend/service/TransactionService.java
src/test/java/capstone/mfslbackend/service/PlayerGameStatsServiceTest.java

**JIRA Ticket:** [CAP-91](https://mfslcapstone.atlassian.net/browse/CAP-91)
---
[CAP-91]: https://mfslcapstone.atlassian.net/browse/CAP-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Small changes

---

src/main/java/capstone/mfslbackend/model/Player.java
src/main/java/capstone/mfslbackend/service/PlayerGameStatsService.java
src/main/java/capstone/mfslbackend/service/PlayerService.java
src/test/java/capstone/mfslbackend/service/PlayerServiceTest.java

**JIRA Ticket:** [CAP-92](https://mfslcapstone.atlassian.net/browse/CAP-92)
---
[CAP-92]: https://mfslcapstone.atlassian.net/browse/CAP-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added points

---

src/main/java/capstone/mfslbackend/service/DraftService.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java

**JIRA Ticket:** [CAP-51](https://mfslcapstone.atlassian.net/browse/CAP-51)
---
[CAP-51]: https://mfslcapstone.atlassian.net/browse/CAP-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix create schedule

---

src/main/java/capstone/mfslbackend/model/Transaction.java
src/main/java/capstone/mfslbackend/service/TransactionService.java
src/test/java/capstone/mfslbackend/service/TransactionServiceTest.java

**JIRA Ticket:** [CAP-89](https://mfslcapstone.atlassian.net/browse/CAP-89)
---
[CAP-89]: https://mfslcapstone.atlassian.net/browse/CAP-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-89: Modify transactions for free agents

---

src/main/java/capstone/mfslbackend/controller/FantasyLeagueController.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java

**JIRA Ticket:** [CAP-100](https://mfslcapstone.atlassian.net/browse/CAP-100)
---
[CAP-100]: https://mfslcapstone.atlassian.net/browse/CAP-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-100: Adding Validation to Join Team

---

src/main/java/capstone/mfslbackend/controller/TransactionController.java
src/main/java/capstone/mfslbackend/service/TransactionService.java

**JIRA Ticket:** [CAP-101](https://mfslcapstone.atlassian.net/browse/CAP-101)
---
[CAP-101]: https://mfslcapstone.atlassian.net/browse/CAP-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make a new endpoint that returns if a free agent signing will be valid

---

src/main/java/capstone/mfslbackend/configuration/WebConfig.java
src/main/java/capstone/mfslbackend/controller/DraftController.java
src/main/java/capstone/mfslbackend/controller/FantasyWeekController.java
src/main/java/capstone/mfslbackend/controller/PlayerController.java
src/main/java/capstone/mfslbackend/controller/StatsController.java
src/main/java/capstone/mfslbackend/controller/TransactionController.java
src/main/java/capstone/mfslbackend/model/FantasyTeam.java
src/main/java/capstone/mfslbackend/model/FantasyWeek.java
src/main/java/capstone/mfslbackend/model/Game.java
src/main/java/capstone/mfslbackend/model/PlayerGameStats.java
src/main/java/capstone/mfslbackend/model/enums/FantasyWeekStatus.java
src/main/java/capstone/mfslbackend/repository/FantasyWeekRepository.java
src/main/java/capstone/mfslbackend/service/DraftService.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java
src/main/java/capstone/mfslbackend/service/FantasyWeekService.java
src/main/java/capstone/mfslbackend/service/PlayerGameStatsService.java
src/main/java/capstone/mfslbackend/service/PlayerService.java
src/main/java/capstone/mfslbackend/service/TransactionService.java
src/test/java/capstone/mfslbackend/service/PlayerGameStatsServiceTest.java

**JIRA Ticket:** [CAP-51](https://mfslcapstone.atlassian.net/browse/CAP-51)
---
[CAP-51]: https://mfslcapstone.atlassian.net/browse/CAP-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAP-51 Fantasy Week

---

src/main/java/capstone/mfslbackend/DTO/DraftDTO.java
src/main/java/capstone/mfslbackend/DTO/FantasyLeagueDTO.java
src/main/java/capstone/mfslbackend/DTO/FantasyTeamWithNoTransactionsNoLeagueDTO.java
src/main/java/capstone/mfslbackend/DTO/PlayerWithNoStatsDTO.java
src/main/java/capstone/mfslbackend/DTO/TransactionDTO.java
src/main/java/capstone/mfslbackend/controller/DraftController.java
src/main/java/capstone/mfslbackend/controller/FantasyWeekController.java
src/main/java/capstone/mfslbackend/controller/TransactionController.java
src/main/java/capstone/mfslbackend/model/FantasyTeam.java
src/main/java/capstone/mfslbackend/model/Transaction.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java
src/main/java/capstone/mfslbackend/service/FantasyWeekService.java
src/main/java/capstone/mfslbackend/service/TransactionService.java

**JIRA Ticket:** [XXX-###](https://mfslcapstone.atlassian.net/browse/XXX-###)
---

Feat/cap 102/fix transaction

---

src/main/java/capstone/mfslbackend/controller/FantasyLeagueController.java
src/main/java/capstone/mfslbackend/service/FantasyLeagueService.java

**JIRA Ticket:** [CAP-42](https://mfslcapstone.atlassian.net/browse/CAP-42)
---
[CAP-42]: https://mfslcapstone.atlassian.net/browse/CAP-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

complete vs incomplete weeks
